### ISSUE TITLE
error compiling all examples

### ISSUE THREAD

**Issue by nassersala** [conal/concat#46]
I'm trying to experiment with the library. Howerer, I can't get it to compile. 

> 🌙 [master*]$ stack build :graphics-examples
> concat-graphics-0.1.0.0: configure (lib + test)
> Configuring concat-graphics-0.1.0.0...
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> concat-graphics-0.1.0.0: build (lib + test)
> Preprocessing library for concat-graphics-0.1.0.0..
> Building library for concat-graphics-0.1.0.0..
> Preprocessing test suite 'graphics-examples' for concat-graphics-0.1.0.0..
> Building test suite 'graphics-examples' for concat-graphics-0.1.0.0..
> [1 of 1] Compiling Main             ( test/Examples.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/graphics-examples/graphics-examples-tmp/Main.o )
> ghc: panic! (the 'impossible' happened)
>   (GHC version 8.2.2 for x86_64-apple-darwin):
>         lam Case of product live wild binder
>   case exr                           
>          @ (->)                      
>          @ (R :* R, (R, R) -> Bool)  
>          @ (R, R)                    
>          $fProductCat(->)            
>          (($fYes1ka @ * @ (R :* R, (R, R) -> Bool), $fYes1ka @ * @ (R, R))
>           `cast` (((%,%)             
>                      (Sym (R:Ok(->)[0]) <((Double, Double),
>                                           (Double, Double) -> Bool)>_N)
>                      (Sym (R:Ok(->)[0]) <(Double, Double)>_N))_R
>                   :: ((Yes1 ((Double, Double), (Double, Double) -> Bool),
>                        Yes1 (Double, Double)) :: Constraint)
>                      ~R#             
>                      ((Ok (->) ((Double, Double), (Double, Double) -> Bool),
>                        Ok (->) (Double, Double)) :: Constraint)))
>          w_g_x_Xi                    
>   of wild_adaJ                       
>   { (a1_adaL, b1_adaM) ->            
>   case a1_adaL of { D# x1_adaQ ->    
>   case exl                           
>          @ (->)                      
>          @ R                         
>          @ R                         
>          $fProductCat(->)            
>          ($d(%,%)_XjKg               
>           `cast` (((%,%)             
>                      (Sym (R:Ok(->)[0]) <R>_N) (Sym (R:Ok(->)[0]) <R>_N))_R
>                   :: ((Yes1 R, Yes1 R) :: Constraint)
>                      ~R#             
>                      ((Ok (->) R, Ok (->) R) :: Constraint)))
>          (exl                        
>             @ (->)                   
>             @ (R :* R)               
>             @ ((R, R) -> Bool)       
>             $fProductCat(->)         
>             (($fYes1ka @ * @ (R, R), $fYes1ka @ * @ ((R, R) -> Bool))
>              `cast` (((%,%)          
>                         (Sym (R:Ok(->)[0]) <(Double, Double)>_N)
>                         (Sym (R:Ok(->)[0]) <(Double, Double) -> Bool>_N))_R
>                      :: ((Yes1 (Double, Double),
>                           Yes1 ((Double, Double) -> Bool)) :: Constraint)
>                         ~R#          
>                         ((Ok (->) (Double, Double),
>                           Ok (->) ((Double, Double) -> Bool)) :: Constraint)))
>             (exl                     
>                @ (->)                
>                @ (R :* R, (R, R) -> Bool)
>                @ (R, R)              
>                $fProductCat(->)      
>                (($fYes1ka @ * @ (R :* R, (R, R) -> Bool), $fYes1ka @ * @ (R, R))
>                 `cast` (((%,%)       
>                            (Sym (R:Ok(->)[0]) <((Double, Double),
>                                                 (Double, Double) -> Bool)>_N)
>                            (Sym (R:Ok(->)[0]) <(Double, Double)>_N))_R
>                         :: ((Yes1 ((Double, Double), (Double, Double) -> Bool),
>                              Yes1 (Double, Double)) :: Constraint)
>                            ~R#       
>                            ((Ok (->) ((Double, Double), (Double, Double) -> Bool),
>                              Ok (->) (Double, Double)) :: Constraint)))
>                w_g_x_Xi))            
>   of                                 
>   { D# y_adaU ->                     
>   case divideC                       
>          @ (->) @ Double $s$fFractionalCat(->)a_shqs (lvl_siqO, boxD y_adaU)
>   of                                 
>   { D# d#_af3a ->                    
>   case mulC                          
>          @ (->) @ Double $s$fNumCat(->)a_shlp (boxD x1_adaQ, boxD d#_af3a)
>   of                                 
>   { D# d#_XfjC ->                    
>   case b1_adaM of { D# x3_adb0 ->    
>   case divideC                       
>          @ (->) @ Double $s$fFractionalCat(->)a_shqs (lvl_siqR, boxD y_adaU)
>   of                                 
>   { D# d#_XfjM ->                    
>   case mulC                          
>          @ (->) @ Double $s$fNumCat(->)a_shlp (boxD x3_adb0, boxD d#_XfjM)
>   of                                 
>   { D# d#_XfjR ->                    
>   case lessThanOrEqual               
>          @ (->)                      
>          @ Double                    
>          $s$fOrdCat(->)a_shnM        
>          (case addC                  
>                  @ (->)              
>                  @ Double            
>                  $s$fNumCat(->)a_shlp
>                  (case mulC          
>                          @ (->) @ Double $s$fNumCat(->)a_shlp (boxD d#_XfjC, boxD d#_XfjC)
>                   of                 
>                   { D# d#_XfjW ->    
>                   boxD d#_XfjW       
>                   },                 
>                   case mulC          
>                          @ (->) @ Double $s$fNumCat(->)a_shlp (boxD d#_XfjR, boxD d#_XfjR)
>                   of                 
>                   { D# d#_XfjW ->    
>                   boxD d#_XfjW       
>                   })                 
>           of                         
>           { D# d#_XfjW ->            
>           boxD d#_XfjW               
>           },                         
>           lvl_siqX)                  
>   of {                               
>     False -> False;                  
>     True ->                          
>       exr                            
>         @ (->)                       
>         @ (R :* R)                   
>         @ ((R, R) -> Bool)           
>         $fProductCat(->)             
>         (($fYes1ka @ * @ (R, R), $fYes1ka @ * @ ((R, R) -> Bool))
>          `cast` (((%,%)              
>                     (Sym (R:Ok(->)[0]) <(Double, Double)>_N)
>                     (Sym (R:Ok(->)[0]) <(Double, Double) -> Bool>_N))_R
>                  :: ((Yes1 (Double, Double),
>                       Yes1 ((Double, Double) -> Bool)) :: Constraint)
>                     ~R#              
>                     ((Ok (->) (Double, Double),
>                       Ok (->) ((Double, Double) -> Bool)) :: Constraint)))
>         (exl                         
>            @ (->)                    
>            @ (R :* R, (R, R) -> Bool)
>            @ (R, R)                  
>            $fProductCat(->)          
>            (($fYes1ka @ * @ (R :* R, (R, R) -> Bool), $fYes1ka @ * @ (R, R))
>             `cast` (((%,%)           
>                        (Sym (R:Ok(->)[0]) <((Double, Double),
>                                             (Double, Double) -> Bool)>_N)
>                        (Sym (R:Ok(->)[0]) <(Double, Double)>_N))_R
>                     :: ((Yes1 ((Double, Double), (Double, Double) -> Bool),
>                          Yes1 (Double, Double)) :: Constraint)
>                        ~R#           
>                        ((Ok (->) ((Double, Double), (Double, Double) -> Bool),
>                          Ok (->) (Double, Double)) :: Constraint)))
>            w_g_x_Xi)                 
>         wild_adaJ                    
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   }                                  
>   Call stack:                        
>       CallStack (from HasCallStack): 
>         prettyCurrentCallStack, called at compiler/utils/Outputable.hs:1133:58 in ghc:Outputable
>         callStackDoc, called at compiler/utils/Outputable.hs:1137:37 in ghc:Outputable
>         pprPanic, called at src/ConCat/Plugin.hs:695:15 in concat-plugin-0.3.0.0-EuTio8PFqXo3nKN9zOJI1b:ConCat.Plugin
>                                      
> Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
>                                      
> Progress 1/2                         
> 
> --  While building custom Setup.hs for package concat-graphics-0.1.0.0 using:
>       /Users/nasser/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 build lib:concat-graphics test:graphics-examples --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
>     Process exited with code: ExitFailure 1
> 🌙 [master*]$ 
> 🌙 [master*]$ 
> 🌙 [master*]$ 
> 🌙 [master*]$ stack build :misc-examples
> concat-examples-0.3.0.0: test (suite: misc-examples)
> 
> 
> 
> curry addC
> Wrote add
> dot -Gsize=10,10 -Tpdf out/add.dot -o out/add.pdf
> /bin/sh: dot: command not found
> misc-examples: user error (command "dot -Gsize=10,10 -Tpdf out/add.dot -o out/add.pdf" failed.)
> 
> concat-examples-0.3.0.0: Test suite misc-examples failed
> Test suite failure for package concat-examples-0.3.0.0
>     misc-examples:  exited with: ExitFailure 1
> Logs printed to console
> 

I'm on macOS 10.13.2
Thanks

**Comment by conal** [comment]
Thanks for the report! I see the compilation failure as well. The same build works fine with GHC 8.0.2, but I recently changed the resolver in stack.yaml to use ghc-8.2.2.

I just pushed a fix. Please try again.

As for "dot: command not found", I just added the following sentence to README.md:

 >
You will need to have [GraphViz](https://www.graphviz.org/) installed, with its `dot` command on your execution path.

**Comment by conal** [comment]
I just noticed that the new Plugin.hs was causing several compiler warnings. Fixed now.

**Comment by capn-freako** [comment]
Okay. I’m not currently using it in Conv; were you thinking that I was?

**Comment by nassersala** [comment]
everything is working now. Thanks! 👍

**Comment by conal** [comment]
Glad to hear it. Thanks for letting me know.
