### ISSUE TITLE
Should this auto diff example work?

### ISSUE THREAD

**Issue by freckletonj** [conal/concat#84]
I'm still getting accustomed to this library+plugin, and I think I'm confusing what happens at what phase. For instance, the following exhausts the rewrite ticks, so I assume there's a rewrite loop. Is it because `deriv` is trying to make the derivative's category `(->)`? I'm really not sure, this all seems quite magical, but in a good way!

```haskell
x :: (Double, Double)
x = let f :: Double -> Double
        f x = x ** 2 + 123
        df :: Double -> (Double -> Double)
        df x = deriv f x
    in (f 10, df 10 10)
```

Any chance I could get a hand with what I'm doing wrong?

**Comment by freckletonj** [comment]
solved it!
```haskell
df :: Double -> (Double -+> Double)
```

let me know how I can help with this library!

**Comment by mikesperber** [comment]
> let me know how I can help with this library!

Just try more stuff and report issues. I would have gotten to this one eventually, was just too slow.

**Comment by conal** [comment]
I appreciate the attention on & help with concat. My recent energy is devoted to reworking the theory and practice of designing and compiling with categories in Agda, this time with elegant formal specifications and proofs.
